### ISSUE TITLE
Temporarily remove or fix Windows image in sbt-github-actions CI

### ISSUE THREAD

**Issue by mdedetrich** [sbt/sbt-github-actions#123]
Currently the CI is broken for Windows (see in progress PR at https://github.com/sbt/sbt-github-actions/pull/121 trying to diagnose why). I have tried to setup this project on a Windows machine to help in finding out the problem but ended up failing to do so due to https://github.com/sbt/sbt-github-actions/issues/122.

@eed3si9n @armanbilge Do you have any qualms in disabling this project on Windows for now? I don't think anyone is developing this plugin on Windows and its very easy to enable later on (just need to adjust https://github.com/sbt/sbt-github-actions/blob/main/build.sbt#L30).

**Comment by armanbilge** [comment]
>  I don't think anyone is developing this plugin on Windows

The reason for Windows in CI is not for development, but for projects that are actually using this plugin on Windows. For example, Cats Effect includes Linux, macOS, and Windows in its CI matrix. If I recall correctly there are some subtle issues with line endings and such that need to be accounted for.

**Comment by mdedetrich** [comment]
>  If I recall correctly there are some subtle issues with line endings and such that need to be accounted for.

So I am trying to solve this in https://github.com/sbt/sbt-github-actions/pull/121 but as far as I can tell it doesn't have anything to do with line endings but rather just finding a specific file.

**Comment by eed3si9n** [comment]
If fixing the test on Windows is not easy, then I think it's fine to comment Windows CI out rather than blocking all other PRs.

**Comment by mdedetrich** [comment]
So I managed to fix the basic issue with the project not being able to load on Windows with https://github.com/sbt/sbt-github-actions/pull/125 however I am now getting problems regarding the tests failing. These problems are different to the CI problems and seems be due to what @armanbilge was mentioning earlier, i.e.

> If I recall correctly there are some subtle issues with line endings and such that need to be accounted for.

I will make a separate issue for this specifically.

**Comment by mdedetrich** [comment]
So after fixing some line break problems in https://github.com/sbt/sbt-github-actions/pull/127 and getting sbt-github-actions to pass all tests on my local Windows machine I think the core problem is something else. When you look at the failures at https://github.com/sbt/sbt-github-actions/actions/runs/3587764952/jobs/6038462004 you can see there are a lot of socket connection issues, i.e. 
```
Error:  java.net.ConnectException: Connection refused: connect
Error:  	at java.base/java.net.PlainSocketImpl.connect0(Native Method)
Error:  	at java.base/java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:101)
Error:  	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)
Error:  	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)
Error:  	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)
Error:  	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
Error:  	at java.base/java.net.Socket.connect(Socket.java:609)
Error:  	at java.base/java.net.Socket.connect(Socket.java:558)
Error:  	at java.base/java.net.Socket.<init>(Socket.java:454)
Error:  	at java.base/java.net.Socket.<init>(Socket.java:264)
Error:  	at xsbt.IPC$.client(IPC.scala:21)
Error:  	at sbt.BasicCommands$.readMessage(BasicCommands.scala:472)
Error:  	at sbt.BasicCommands$.doRead(BasicCommands.scala:448)
Error:  	at sbt.BasicCommands$.$anonfun$read$2(BasicCommands.scala:435)
Error:  	at sbt.Command$.$anonfun$applyEffect$4(Command.scala:150)
Error:  	at sbt.Command$.$anonfun$applyEffect$2(Command.scala:145)
Error:  	at sbt.Command$.process(Command.scala:189)
Error:  	at sbt.MainLoop$.$anonfun$processCommand$5(MainLoop.scala:245)
Error:  	at scala.Option.getOrElse(Option.scala:189)
Error:  	at sbt.MainLoop$.process$1(MainLoop.scala:245)
Error:  	at sbt.MainLoop$.processCommand(MainLoop.scala:276)
Error:  	at sbt.MainLoop$.$anonfun$next$5(MainLoop.scala:163)
Error:  	at sbt.State$StateOpsImpl$.runCmd$1(State.scala:289)
Error:  	at sbt.State$StateOpsImpl$.process$extension(State.scala:325)
Error:  	at sbt.MainLoop$.$anonfun$next$4(MainLoop.scala:163)
Error:  	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
Error:  	at sbt.MainLoop$.next(MainLoop.scala:163)
Error:  	at sbt.MainLoop$.run(MainLoop.scala:144)
Error:  	at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:119)
Error:  	at sbt.io.Using.apply(Using.scala:27)
Error:  	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:112)
Error:  	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:66)
Error:  	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:51)
Error:  	at sbt.MainLoop$.runLogged(MainLoop.scala:42)
Error:  	at sbt.StandardMain$.runManaged(Main.scala:218)
Error:  	at sbt.xMain$.$anonfun$run$11(Main.scala:133)
Error:  	at sbt.internal.util.Terminal$.withStreams(Terminal.scala:[381](https://github.com/sbt/sbt-github-actions/actions/runs/3587764952/jobs/6038462004#step:8:382))
Error:  	at sbt.xMain$.withStreams$1(Main.scala:87)
Error:  	at sbt.xMain$.run(Main.scala:121)
Error:  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Error:  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
Error:  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Error:  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
Error:  	at sbt.internal.XMainConfiguration.run(XMainConfiguration.java:56)
Error:  	at sbt.xMain.run(Main.scala:46)
Error:  	at xsbt.boot.Launch$.$anonfun$run$1(Launch.scala:149)
Error:  	at xsbt.boot.Launch$.withContextLoader(Launch.scala:176)
Error:  	at xsbt.boot.Launch$.run(Launch.scala:149)
Error:  	at xsbt.boot.Launch$.$anonfun$apply$1(Launch.scala:44)
Error:  	at xsbt.boot.Launch$.launch(Launch.scala:159)
Error:  	at xsbt.boot.Launch$.apply(Launch.scala:44)
Error:  	at xsbt.boot.Launch$.apply(Launch.scala:21)
Error:  	at xsbt.boot.Boot$.runImpl(Boot.scala:78)
Error:  	at xsbt.boot.Boot$.run(Boot.scala:73)
Error:  	at xsbt.boot.Boot$.main(Boot.scala:21)
Error:  	at xsbt.boot.Boot.main(Boot.scala)
```

I think the problem here is that the Windows image in the CI is restricting the default port that is being used by the sbt server/client. @eed3si9n Maybe you have some idea here?

**Comment by mdedetrich** [comment]
So I found out from the sbt discord that this is not an isolated issue, it appears that scripted tests in general don't work in the github actions Windows CI, so I made a general issue on sbt at https://github.com/sbt/sbt/issues/7082
