### ISSUE TITLE
Force rebase/squash and merge for pull requests

### ISSUE THREAD

**Issue by mdedetrich** [sbt/sbt-github-actions#129]
I am personally not fond of using merge commits on pull requests because they add a lot of extra noise onto the git history (in other words I prefer to work with a linear history which is achieved by rebase or squash + merge).

@eed3si9n @armanbilge How do feel about disabling merge commits for PR's, i.e. forcing linear history? If you are happy with this I can update the settings for this repo plus I can remove the merge commits from the current main.

**Comment by armanbilge** [comment]
> plus I can remove the merge commits from the current main

As in, re-writing git history? If you don't mind me saying, that seems rather drastic :)

> I am personally not fond of using merge commits on pull requests because they add a lot of extra noise onto the git history

Historically, this repository is using merge commits, as are most of Daniel's other projects and most Typelevel projects. In practice, it seems to be a matter of personal taste. I prefer merges and also not changing the status quo: that is to say, if this project was already enforcing linear history, I'd say we can stick to that.

**Comment by mdedetrich** [comment]
No worries, I am not going to die on this hill and I don't

> As in, re-writing git history? If you don't mind me saying, that seems rather drastic :)

Removal of merge commits doesn't end up breaking anything for end users because merge commits have no content but since I won't go ahead with it its not that relevant (I have also done it before).

> that is to say, if this project was already enforcing linear history, I'd say we can stick to that.

To be clear, I assume you are talking about projects in general here and not this project specifically (sbt-github-actions doesn't have a linear history because it has merge commits).
