### ISSUE TITLE
"Integration with sbt-ci-release" generates cross build

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt-github-actions#138]
## steps

Follow "Integration with sbt-ci-release" section in the readme.

## problem

It generates

https://github.com/sbt/sbt-github-actions/blob/330e5613f242dfcc9967991ae3da13b63516f8ec/.github/workflows/ci.yml#L127-L132

## expectation

Cross building `++${{ matrix.scala }}` should not be used for sbt-ci-release, which internally already calls `+publishSigned` or whatever the user has configured.

**Comment by armanbilge** [comment]
This is not a problem, or at least a superficial one. `++${{ matrix.scala }}` does not generate a cross build, it merely sets a Scala version. As you point out, sbt-ci-release already runs `+publish`. So it does not matter whether or not you set the Scala version.

**Comment by eed3si9n** [comment]
I think this *could* lead to a subtle breakage since the switch command can push the build settings to a `crossScalaVersions`-listed, but non-default Scala version. We also saw it break by `++${{ matrix.scala }}` not matching up with `crossScalaVersions` in case `ThisBuild/scalaVersion` is not set.

**Comment by eed3si9n** [comment]
Here's my PR for this - https://github.com/sbt/sbt-github-actions/pull/139
