### ISSUE TITLE
Pull request can trigger two workflow runs

### ISSUE THREAD

**Issue by mzuehlke** [sbt/sbt-github-actions#145]
When setting up `sbt-github-actions` for an internal project I found when creating pull-request from branches on the same repo the workflows are executed twice. Once for the push to the branch and a 2nd time for the pull-request.

A short search revealed a way to prevent this: 
- https://github.com/zopefoundation/meta/issues/145

Without editing the `ci.yml` by hand this can be added to the `build` job using the plugin syntax:
```Scala
ThisBuild / githubWorkflowGeneratedCI ~= {
  _.map { job =>
    if (job.id == "build")
      job.copy(cond = Some("github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name"))
    else job
  }
}
```

While adding this condition manually is possible, in my opinion this could be added to the default configuration.
If there are no objections, I can provide a PR.

**Comment by armanbilge** [comment]
This issue is here:
https://github.com/sbt/sbt-github-actions/blob/aaf1a144407e2db3672a15ca6fd62b774fbf5899/.github/workflows/ci.yml#L10-L15

If you don't want CI to run on pushes to certain branches, you can modify that setting.

**Comment by armanbilge** [comment]
Oh I see, you want a complex rule that only runs if there isn't an existing PR for that branch?

> But you can not specify different branches for `pull_request` and for `push` 😢 So this is not possible.

Why do you need different values for there? If you don't want to run CI on a branch, I'm guessing you don't want CI for PRs _targeting_ that branch either? PRs _from_ that branch to your main branch will still have CI of course.

**Comment by mzuehlke** [comment]
That was **my misunderstanding**. That the branch names for `pull_request` are about the **target** branch 🤦
