### ISSUE TITLE
Please make a release!

### ISSUE THREAD

**Issue by tusharmath** [sbt/sbt-github-actions#154]
The last release was in Dec 2021, after which many contributors have fixed bugs and added features. Would humbly request you to make a new release!

**Comment by eed3si9n** [comment]
@sbt/sbt-github-actions Unless there's an objection, I'll try to cut a release today, or this weekend.

**Comment by mdedetrich** [comment]
There was one feature that I wanted to get in but its not urgent and considering how long the last release was I think making one is more important.

@armanbilge Do you have anything to add?

**Comment by eed3si9n** [comment]
See also https://repo1.maven.org/maven2/com/github/sbt/sbt-github-actions_2.12_1.0/0.15.0-M1/

**Comment by hagay3** [comment]
+1

**Comment by eed3si9n** [comment]
https://github.com/sbt/sbt-github-actions/releases/tag/v0.15.0 is out
