### ISSUE TITLE
clean.yml doesn't respect githubWorkflowOSes

### ISSUE THREAD

**Issue by custommonkey** [sbt/sbt-github-actions#159]
clean.yml doesn't respect **runs-on** condition set in `githubWorkflowOSes`, hard coded value of `ubuntu-latest` may not work in hosted environments.

**Comment by mdedetrich** [comment]
So I started some work on this at https://github.com/sbt/sbt-github-actions/pull/167 however it will take some time to finish off due to the fact that the current `clean.yml` script is not portable for windows (even when running under Windows bash there appears to be some issues).

**Comment by mdedetrich** [comment]
Red herring, PR is ready just need someone else to review it

**Comment by mdedetrich** [comment]
@custommonkey v0.18.0 was just released with this feature added, can you please confirm that it works?

**Comment by custommonkey** [comment]
Thank you very much for this. clean is working as I expected. 

I have noticed that the publish phase doesn't use the configured OS I hope submitted a PR to address this when I get some time.

**Comment by mdedetrich** [comment]
> Thank you very much for this. clean is working as I expected. 
> 
> I have noticed that the publish phase doesn't use the configured OS I hope submitted a PR to address this when I get some time. 

Is the reason behind why publishes phase is not working due to the shell script not running or something else?

**Comment by custommonkey** [comment]
The `WorkflowJob` for `publish` doesn't use `githubWorkflowOSes` to set `oses` in the same way as the `build` step does. So the default value from `WorkflowJob` is used.

**Comment by mdedetrich** [comment]
@custommonkey PR created at https://github.com/sbt/sbt-github-actions/pull/169

**Comment by mdedetrich** [comment]
@custommonkey `v0.19.0` was just released with this fix, let me know if there are any additional issues.

**Comment by custommonkey** [comment]
Thanks that's working. I now have a separate issue that the v4 of the the checkout action isn't compatible with our enterprise version.

**Comment by mdedetrich** [comment]
> Thanks that's working. I now have a separate issue that the v4 of the the checkout action isn't compatible with our enterprise version.

Hmm I am on the fence on this one, sounds like its a problem for github enterprise and/or checkout action to solve, no?

**Comment by custommonkey** [comment]
Yep
