### ISSUE TITLE
exposing base directory for monorepo support

### ISSUE THREAD

**Issue by rurouni-najeeb** [sbt/sbt-github-actions#161]
Wondering if there is a way to put the generated `ci.yml` as well as the `clean.yml` into a different folder to better support monorepos? In my organisation, we have a monorepo where all the GitHub actions are consolidated in a singular `.github` directory at the root level of the repo.

Thanks a ton for the cool tooling around GitHub Actions 💯

**Comment by mdedetrich** [comment]
@rurouni-najeeb Is there github documentation on how to do this?

**Comment by rurouni-najeeb** [comment]
@mdedetrich in my limited experience with the tooling, I am not really sure if the feature already exists. I was wondering if something of a `SettingKey` like `This Build / githubWorkflowDir` would be a nice option to have so that the CI code is generated in that specific directory. 
I believe that it should be possible to add it [here](https://github.com/sbt/sbt-github-actions/blob/04f573a1708e455081218d76fc0c61bef09a4b9b/src/main/scala/sbtghactions/GenerativePlugin.scala#L796C21-L796C34) and fall back to the `baseDirectory` if the SettingKey is not found? 🤔

**Comment by mdedetrich** [comment]
The sbt side of things (i.e. what sbt setting to use) isn't the problematic part, its more how github ci works with different directories.

Or is just that you want to literally control which folder the generated `.yml` files get placed and thats it? If so this shouldn't be hard to implement.

**Comment by rurouni-najeeb** [comment]
Ah I interpreted it incorrectly. But yeah in essence it would be nice to control where the generated CI could be put (like the directory name). This would inherently provide support for monorepos. For example in our case we have the following structure
```markdown
.
├── .github
│   └── workflows
│       ├── workflow1.yml <-- this could be a workflow for project-1
│       └── workflow2.yml <-- this could be a workflow for project-2
├── project-1
│   └── someFile.scala
|   └── build.sbt
├── project-2
│   └── someFile.ext
└── project-3
    └── someFile.ext
```
and assuming `project-1` is one of the projects where the plugin is getting used, we would like to declare the CI configuration in `project-1/build.sbt` but the workflow should get generated in `.github/workflows`

**Comment by mdedetrich** [comment]
PR made at https://github.com/sbt/sbt-github-actions/pull/166

**Comment by armanbilge** [comment]
@rurouni-najeeb instead of us supporting this explicitly, could you use symlinks?

**Comment by mdedetrich** [comment]
> @rurouni-najeeb instead of us supporting this explicitly, could you use symlinks?

What is the harm in making this configurable? I mean if you look at the PR the change is trivial, it's not really adding any maintenance burden.

I could also imagine that depending on the context, using symlinks could be problematic.

**Comment by mdedetrich** [comment]
@armanbilge Do you still have an issue with this, PR is already ready and approved. I want to get started on upstream the sbt-typelevel stuff, if you had concerns over difficulty on making a release this shouldn't be a concern (I have permissions to make a release and due to sbt-ci-release its really easy to do since I can just push a git tag).

**Comment by rurouni-najeeb** [comment]
Sorry everyone for a late response. Thanks for the PR @mdedetrich
@armanbilge, I would not like to use a symlink because then we might have to deviate from one of the patterns that we have inside our monorepo where we put all the actions in a singular place. A configurable directory (as I understand from @mdedetrich, does not require any maintainence) would I guess also be a nice option given the whole lot of configurations that tooling already provides :)

**Comment by mdedetrich** [comment]
@armanbilge  So I am going to go ahead and merge the PR at https://github.com/sbt/sbt-github-actions/pull/166 (which will close this issue) since the its been sitting there for a while.

In the worst case scenario we can always deprecate this setting and eventually remove it (sbt-github-actions version is 0.x so this is easier to do).

**Comment by mdedetrich** [comment]
@rurouni-najeeb 0.17.0 was just released with this change, please let me know if there are any issues
