### ISSUE TITLE
macos-latest no longer has `sbt` installed by default

### ISSUE THREAD

**Issue by SethTisue** [sbt/sbt-github-actions#185]
as per https://github.com/actions/setup-java/issues/625, I think this plugin needs to be updated to do `brew install sbt` for MacOS jobs

**Comment by eed3si9n** [comment]
`ubuntu-24.04` image is also missing `sbt` runner script. I've created a new GitHub Action called `sbt/setup-sbt` - https://eed3si9n.com/setup-sbt/

**Comment by eed3si9n** [comment]
Here's my PR for this - https://github.com/sbt/sbt-github-actions/pull/187

**Comment by eed3si9n** [comment]
See https://github.com/sbt/setup-sbt/issues/2. I need to fix the action probably by copying to another repo /cc @mdedetrich

**Comment by eed3si9n** [comment]
I was able to register the action under a different name https://github.com/marketplace/actions/setup-sbt-installer, so maybe we'd be ok?
