### ISSUE TITLE
Enhancement: add githubWorkflowPublishScalaVersions

### ISSUE THREAD

**Issue by pjfanning** [sbt/sbt-github-actions#85]
* this would default to the value of githubWorkflowScalaVersions (which defaults to crossScalaVersions)
* it would control which versions of scala have jars published
* specifically, I would like to have crossScalaVersions contain 3.0.2 and 3.1.0 (so I can test with both versions) but only publish for scala 3.0.2. My understanding is that for maximum Scala 3 compatibility, it is best to publish Scala 3 artifacts that are built with scala 3.0.x. These will run ok on Scala 3.1.x. But artifacts built with Scala 3.1.x won't work on Scala 3.0.x. See https://twitter.com/SethTisue/status/1450260785762947076

**Comment by djspiewak** [comment]
I like this idea a lot but it's going to get slightly tricky. :-) We basically delegate the semantics of "which version to release for" back to `sbt` in the form of the release action(s), which are configurable but have no direct knowledge of Scala version. I'm not sure exactly how to do what you're suggesting without making a lot of assumptions about how the release process works for the given build.

**Comment by pjfanning** [comment]
https://typelevel.org/sbt-typelevel/gha.html now supports building just once per Scala point release (only 1 build for Scala 3)
